[package]
name = 'coin'
version = '1.0.0'

[addresses]
coin = "0x1"
Std = "0x1"
aptos_std = "0x1"

[dependencies]
MoveStdlib = { git = "https://github.com/diem/diem.git", subdir="language/move-stdlib", rev = "56ab033cc403b489e891424a629e76f643d4fb6b", addr_subst = { "Std" = "0x1" } }
